name: prod-stage

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Prerelease version to deploy (e.g., v1.0.4-rc)'
        required: true
        type: string

concurrency:
  group: prod-stage
  cancel-in-progress: true

jobs:
  generate-production-version:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    outputs:
      production-version: ${{ steps.generate-version.outputs.version }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Generate Production Version
        id: generate-version
        uses: optivem/generate-release-version-action@v1
        with:
          prerelease-version: ${{ inputs.version }}

  check-release-exists:
    needs: generate-production-version
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Check Version Release Exists
        id: check-release
        uses: optivem/check-release-exists-action@v1
        with:
          version: ${{ inputs.version }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  resolve-docker-images:
    needs: [generate-production-version, check-release-exists]
    if: needs.check-release-exists.result == 'success'
    runs-on: ubuntu-latest
    outputs:
      image-urls: ${{ steps.resolve-images.outputs.image-urls }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Resolve Docker Images
        id: resolve-images
        uses: optivem/resolve-docker-images-action@v1
        with:
          tag: ${{ inputs.version }}
          base-image-urls: |
            ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}/monolith

  tag-docker-images:
    needs: [generate-production-version, check-release-exists, resolve-docker-images]
    if: needs.resolve-docker-images.result == 'success'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    outputs:
      image-urls: ${{ steps.tag-images.outputs.image-urls }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Tag Docker Images for Production
        id: tag-images
        uses: optivem/tag-docker-images-action@v1
        with:
          image-urls: ${{ needs.resolve-docker-images.outputs.image-urls }}
          tag: ${{ needs.generate-production-version.outputs.production-version }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  deploy-docker-images:
    needs: [generate-production-version, check-release-exists, tag-docker-images]
    if: needs.tag-docker-images.result == 'success'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Deploy System
        id: deploy
        uses: ./.github/actions/deploy-docker-images
        with:
          environment: production
          version: ${{ needs.generate-production-version.outputs.production-version }}
          image-urls: ${{ needs.tag-docker-images.outputs.image-urls }}

  production-release:
    needs: [generate-production-version, tag-docker-images, deploy-docker-images]
    if: needs.deploy-docker-images.result == 'success'
    runs-on: ubuntu-latest
    permissions:
      contents: write
    outputs:
      release-url: ${{ steps.create-release.outputs.release-url }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Create Production Release
        id: create-release
        uses: optivem/create-release-action@v1
        with:
          base-version: ${{ inputs.version }}
          release-version: ${{ needs.generate-production-version.outputs.production-version }}
          environment: prod
          status: deployed
          artifact-urls: ${{ needs.tag-docker-images.outputs.image-urls }}
          is-prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  summary:
    needs: [generate-production-version, check-release-exists, resolve-docker-images, tag-docker-images, deploy-docker-images, production-release]
    if: always() # Run even if previous jobs fail
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
      
    - name: Generate Production Stage Summary
      uses: optivem/summarize-system-stage-action@v1
      with:
        stage-name: 'Production Stage'
        environment: production
        stage-result: ${{ needs.production-release.result }}
        success-version: ${{ needs.generate-production-version.outputs.production-version }}
        success-artifact-ids: ${{ needs.tag-docker-images.outputs.image-urls }}
