name: qa-signoff

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version that was tested in QA (e.g., v1.0.4-rc)'
        required: true
        type: string
      result:
        description: 'QA testing result'
        required: true
        type: choice
        options:
          - success
          - failure

concurrency:
  group: qa-signoff
  cancel-in-progress: true

jobs:
  check-version-exists:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Check Version Release Exists
        uses: optivem/check-release-exists-action@v1
        with:
          version: ${{ inputs.version }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  signoff-status-version:
    needs: check-version-exists
    if: needs.check-version-exists.result == 'success'
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.generate-version.outputs.version }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Generate Signoff Status Version
        id: generate-version
        uses: optivem/generate-status-version-action@v1
        with:
          version: ${{ inputs.version }}
          environment: qa
          status: ${{ inputs.result }}

  signoff-release:
    needs: signoff-status-version
    if: needs.signoff-status-version.result == 'success'
    runs-on: ubuntu-latest
    permissions:
      contents: write
    outputs:
      release-url: ${{ steps.create-release.outputs.release-url }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Create Signoff Release
        id: create-release
        uses: optivem/create-release-action@v1
        with:
          base-version: ${{ inputs.version }}
          release-version: ${{ needs.signoff-status-version.outputs.version }}
          environment: qa
          status: ${{ inputs.result }}
          is-prerelease: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  summary:
    needs: [check-version-exists, signoff-status-version, signoff-release]
    if: always() # Run even if previous jobs fail
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
      
    - name: Determine Stage Result
      id: determine-result
      run: |
        if [[ "${{ needs.signoff-release.result }}" == "success" && "${{ inputs.result }}" == "success" ]]; then
          echo "stage-result=success" >> $GITHUB_OUTPUT
          echo "✅ Both workflow execution and QA testing were successful"
        else
          echo "stage-result=failure" >> $GITHUB_OUTPUT
          echo "❌ Either workflow execution failed or QA testing failed"
          echo "Workflow result: ${{ needs.signoff-release.result }}"
          echo "QA test result: ${{ inputs.result }}"
        fi
      shell: bash
      
    - name: Generate QA Signoff Stage Summary
      uses: optivem/summarize-system-stage-action@v1
      with:
        stage-name: 'QA Signoff'
        environment: qa
        stage-result: ${{ steps.determine-result.outputs.stage-result }}
        success-version: ${{ needs.signoff-status-version.outputs.version }}
